#!/bin/bash
# NOTE: The purpose of this script is to fix the UI static bundle generated by beaker.
# It is hardcoded to load assets off of the website's root, which breaks functionality
# on HeLx deployments.

BEAKER_LOCATION=$(python -c "import beaker_kernel; import os; print(os.path.dirname(beaker_kernel.__file__))")
UI_INDEX="$BEAKER_LOCATION/service/ui/index.html"
STATIC_FILES="$BEAKER_LOCATION/service/ui/static"
# Remove leading slash.
NB_PREFIX_RELATIVE=${NB_PREFIX#/}

# Replace static URLs hard-coded to root `/`
sed -i \
    -e "s|/static|$NB_PREFIX/static|g" \
    -e "s|/favicon|$NB_PREFIX/favicon|g" \
    "$UI_INDEX"

# Replace config URLs and static URLs hard-coded to root.
for FILE in $STATIC_FILES/*; do
    if [[ -f "$FILE" ]]; then
        if ! sed -i \
            -e "s|p(\"baseUrl\")|\"$NB_PREFIX\"|g" \
            -e "s|static/|$NB_PREFIX_RELATIVE/static/|g" \
            -e "s|/themes|$NB_PREFIX/themes|g" \
            -e "s|/files|$NB_PREFIX/files|g" \
            -e "s|\`/integrations|\`$NB_PREFIX/integrations|g" \
            -e "s|\`/beaker/integrations|\`$NB_PREFIX/beaker/integrations|g" \
            -e "s|chat?.default ? \"\" : \"chat\"|chat?.default ? \"$NB_PREFIX_RELATIVE\" : \"$NB_PREFIX_RELATIVE/chat\"|g" \
            -e "s|notebook?.default ? \"\" : \"notebook\"|notebook?.default ? \"$NB_PREFIX_RELATIVE\" : \"$NB_PREFIX_RELATIVE/notebook\"|g" \
            -e "s|href: \"/chat\"|href: \"$NB_PREFIX/chat\"|g" \
            -e "s|href: \"/notebook\"|href: \"$NB_PREFIX/notebook\"|g" \
            -e "s|ath: \"/|ath: \"$NB_PREFIX/|g" \
            -e "s|alias = \"/|alias = \"$NB_PREFIX|g" \
            "$FILE";
        then
            echo "Sed substitution failed on $FILE, skipping..."
        fi
    fi
done